const state={apps:[],selected:null,tab:'apps'}; const $=s=>document.querySelector(s); const token=()=>localStorage.getItem('pm_token');
async function api(url,opt={}){opt.headers={...(opt.headers||{}),'Content-Type':'application/json'};if(token())opt.headers.Authorization='Bearer '+token();const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
async function loadApps(){state.apps=await api('/api/apps');render()}
function render(){const list=$('#platforms');const q=($('#search').value||'').toLowerCase();const arr=(state.tab==='my'?state.my||[]:state.apps).filter(a=>a.name.toLowerCase().includes(q));list.innerHTML=arr.length?arr.map(a=>`<article class="card" data-id="${a._id}">${a.logo?`<img class="logo" src="${a.logo}" alt="">`:`<div class="logo fallback">${a.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div>`}<div class="info"><h2>${a.name}</h2><p>${a.description||''}</p></div><div class="arrow">→</div></article>`).join(''):`<div class="empty">${state.tab==='my'?'Abhi koi purchased app nahi hai.':'No apps found.'}</div>`;list.querySelectorAll('.card').forEach(c=>c.onclick=()=>select(c.dataset.id));$('#appsTab').classList.toggle('active',state.tab==='apps');$('#myTab').classList.toggle('active',state.tab==='my');}
async function select(id){const a=(state.tab==='my'?state.my:state.apps).find(x=>x._id===id);if(!a)return;state.selected=a;$('#selected').textContent=a.name+' selected — Premium ₹'+a.price+' required.';$('#premium').classList.remove('hidden');$('#premium').scrollIntoView({behavior:'smooth',block:'center'});}
function openTelegram(){const name=state.selected?.name||'platform';location.href='https://t.me/Subhanali011?text='+encodeURIComponent(`Mujhe ${name} ka premium khareedna hai.`)}
async function myApps(){if(!token()){showAuth();return}state.my=await api('/api/my-apps');state.tab='my';render()}
function showAuth(){ $('#auth').classList.remove('hidden') } function closeAuth(){$('#auth').classList.add('hidden')}
async function authSubmit(){try{const u=$('#username').value,p=$('#password').value;const d=await api($('#authMode').value==='login'?'/api/login':'/api/register',{method:'POST',body:JSON.stringify({username:u,password:p})});localStorage.setItem('pm_token',d.token);closeAuth();await myApps()}catch(e){alert(e.message)}}
async function redeem(){if(!token()){showAuth();return}try{const d=await api('/api/verify-code',{method:'POST',body:JSON.stringify({code:$('#code').value})});alert(d.message);$('#code').value='';state.my=await api('/api/my-apps');state.tab='my';render()}catch(e){alert(e.message)}}
$('#search').oninput=render;$('#appsTab').onclick=()=>{state.tab='apps';render()};$('#myTab').onclick=myApps;$('#buy').onclick=openTelegram;$('#redeem').onclick=redeem;$('#loginBtn').onclick=showAuth;$('#authSubmit').onclick=authSubmit;$('#authClose').onclick=closeAuth;$('#toggleAuth').onclick=()=>{$('#authMode').value=$('#authMode').value==='login'?'register':'login';$('#authSubmit').textContent=$('#authMode').value==='login'?'LOGIN':'CREATE ACCOUNT';$('#toggleAuth').textContent=$('#authMode').value==='login'?'Create account':'Back to login'};
window.addEventListener('load',async()=>{await loadApps();setTimeout(()=>$('#telegramPopup').classList.remove('hide'),250)});
function closePopup(){$('#telegramPopup').classList.add('hide')}
