require('dotenv').config();
const express=require('express'); const mongoose=require('mongoose'); const bcrypt=require('bcryptjs'); const jwt=require('jsonwebtoken'); const crypto=require('crypto'); const path=require('path'); const multer=require('multer');
const app=express(); app.use(express.json({limit:'3mb'})); app.use(express.static(path.join(__dirname)));
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:2*1024*1024},fileFilter:(req,file,cb)=>{if(/^image\/(png|jpeg|jpg|webp|gif)$/.test(file.mimetype))cb(null,true);else cb(new Error('Only PNG, JPG, WEBP or GIF images are allowed'))}});
const App=mongoose.model('App',new mongoose.Schema({name:{type:String,required:true},description:String,logo:String,authorizedUrl:String,price:{type:Number,default:100},active:{type:Boolean,default:true}},{timestamps:true}));
const User=mongoose.model('User',new mongoose.Schema({username:{type:String,unique:true,required:true},passwordHash:String,purchasedApps:[{type:mongoose.Schema.Types.ObjectId,ref:'App'}]},{timestamps:true}));
const Code=mongoose.model('PremiumCode',new mongoose.Schema({codeHash:{type:String,unique:true},appId:{type:mongoose.Schema.Types.ObjectId,ref:'App'},status:{type:String,enum:['active','revoked'],default:'active'},createdAt:{type:Date,default:Date.now},usedAt:Date,usedBy:{type:mongoose.Schema.Types.ObjectId,ref:'User'}},{timestamps:true}));
const SiteSettings=mongoose.model('SiteSettings',new mongoose.Schema({key:{type:String,unique:true,default:'main'},data:{type:Object,default:{}}},{timestamps:true}));
const admin={username:process.env.ADMIN_USERNAME||'admin',password:process.env.ADMIN_PASSWORD||'change-me'};
function sign(u){return jwt.sign({id:u._id,username:u.username},process.env.JWT_SECRET||'dev-secret-change-me',{expiresIn:'7d'})}
function auth(req,res,next){try{const h=req.headers.authorization||''; const t=h.startsWith('Bearer ')?h.slice(7):''; req.user=jwt.verify(t,process.env.JWT_SECRET||'dev-secret-change-me'); next()}catch(e){res.status(401).json({error:'Login required'})}}
function adminAuth(req,res,next){if(req.headers['x-admin-token']!=='ADMIN_PANEL_TOKEN_CHANGE_ME') return res.status(401).json({error:'Admin login required'}); next()}
function makeCode(){return 'PM-'+crypto.randomBytes(6).toString('hex').toUpperCase().match(/.{1,4}/g).join('-')}
async function hashCode(c){return crypto.createHash('sha256').update(c).digest('hex')}
app.post('/api/register',async(req,res)=>{try{const {username,password}=req.body;if(!username||!password||password.length<6)return res.status(400).json({error:'Username and password (6+ chars) required'});const exists=await User.findOne({username});if(exists)return res.status(409).json({error:'Username already exists'});const u=await User.create({username,passwordHash:await bcrypt.hash(password,12),purchasedApps:[]});res.json({token:sign(u),username:u.username})}catch(e){res.status(500).json({error:'Registration failed'})}});
app.post('/api/login',async(req,res)=>{try{const {username,password}=req.body;const u=await User.findOne({username});if(!u||!(await bcrypt.compare(password,u.passwordHash)))return res.status(401).json({error:'Invalid login'});res.json({token:sign(u),username:u.username})}catch(e){res.status(500).json({error:'Login failed'})}});

const defaultSettings={siteLogo:'assets/prep-master.png',brandName:'PREP MASTER',heroEyebrow:'SELECT ECOSYSTEM',heroTitle:'Choose',heroAccent:'Platform',heroSubtitle:'Select a platform to continue.',searchPlaceholder:'Search for a platform or feature...',appsTabLabel:'Apps',myAppsTabLabel:'My Apps',loginLabel:'Login',footerText:'DEVLOPWD BY',footerName:'SUBHAN ALI',popupTitle:'Stay Connected',popupText:'Latest updates aur important announcements ke liye hamare Telegram channel se connected rahein.',popupButtonText:'JOIN TELEGRAM NOW',popupContinueText:'I UNDERSTAND, CONTINUE',telegramUrl:'https://t.me/prepmaster0',backText:'← BACK TO APPS',detailLabel:'SELECTED PLATFORM',premiumTitle:'Premium Access',premiumTextTemplate:'{name} ka premium access — ₹{price}.',buyTextTemplate:'BUY NOW — ₹{price}',selectedTextTemplate:'{name} selected — Premium ₹{price} required.',codePlaceholder:'Enter Premium Code',verifyText:'VERIFY CODE'};
app.get('/api/settings',async(req,res)=>{const doc=await SiteSettings.findOne({key:'main'});res.json({...defaultSettings,...(doc?.data||{})})});
app.get('/api/admin/settings',adminAuth,async(req,res)=>{const doc=await SiteSettings.findOne({key:'main'});res.json({...defaultSettings,...(doc?.data||{})})});
app.put('/api/admin/settings',adminAuth,async(req,res)=>{const allowed=Object.keys(defaultSettings);const data={};for(const k of allowed){if(req.body[k]!==undefined)data[k]=String(req.body[k]);}const doc=await SiteSettings.findOneAndUpdate({key:'main'},{$set:{data}},{upsert:true,new:true,setDefaultsOnInsert:true});res.json({...defaultSettings,...doc.data})});

app.get('/api/apps',async(req,res)=>{res.json(await App.find({active:true}).sort({createdAt:1}))});
app.get('/api/my-apps',auth,async(req,res)=>{const u=await User.findById(req.user.id).populate('purchasedApps');res.json(u?.purchasedApps?.filter(a=>a.active&&a.authorizedUrl)||[])});
app.post('/api/verify-code',auth,async(req,res)=>{try{const raw=(req.body.code||'').trim().toUpperCase();const appId=(req.body.appId||'').trim();if(!raw)return res.status(400).json({error:'Code required'});if(!appId)return res.status(400).json({error:'App select karo'});const c=await Code.findOne({codeHash:await hashCode(raw),status:'active',appId});if(!c)return res.status(400).json({error:'Invalid code or code is for another app'});const u=await User.findById(req.user.id);if(!u)return res.status(401).json({error:'Login required'});if(!u.purchasedApps.some(x=>String(x)===String(c.appId)))u.purchasedApps.push(c.appId);c.status='revoked';c.usedAt=new Date();c.usedBy=u._id;await Promise.all([u.save(),c.save()]);const a=await App.findById(c.appId);res.json({ok:true,app:a?.authorizedUrl?{name:a.name,url:a.authorizedUrl}:null,message:'Premium activated successfully'})}catch(e){res.status(500).json({error:'Verification failed'})}});
app.post('/api/admin/login',async(req,res)=>{const {username,password}=req.body;if(username===admin.username&&password===admin.password)return res.json({token:'ADMIN_PANEL_TOKEN_CHANGE_ME'});res.status(401).json({error:'Invalid admin login'})});
app.post('/api/admin/upload-image',adminAuth,upload.single('image'),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:'Image file required'});const data='data:'+req.file.mimetype+';base64,'+req.file.buffer.toString('base64');res.json({url:data})}catch(e){res.status(400).json({error:e.message||'Image upload failed'})}});
app.get('/api/admin/apps',adminAuth,async(req,res)=>res.json(await App.find().sort({createdAt:1})));
app.post('/api/admin/apps',adminAuth,async(req,res)=>{const a=await App.create(req.body);res.json(a)});
app.put('/api/admin/apps/:id',adminAuth,async(req,res)=>{const a=await App.findByIdAndUpdate(req.params.id,req.body,{new:true});res.json(a)});
app.delete('/api/admin/apps/:id',adminAuth,async(req,res)=>{await App.findByIdAndDelete(req.params.id);res.json({ok:true})});
app.post('/api/admin/codes',adminAuth,async(req,res)=>{const {appId}=req.body;if(!await App.exists({_id:appId}))return res.status(400).json({error:'App not found'});const plain=makeCode();await Code.create({codeHash:await hashCode(plain),appId});res.json({code:plain})});
app.get('/api/admin/codes',adminAuth,async(req,res)=>res.json(await Code.find().populate('appId','name').sort({createdAt:-1})));
app.post('/api/admin/codes/:id/revoke',adminAuth,async(req,res)=>{await Code.findByIdAndUpdate(req.params.id,{status:'revoked'});res.json({ok:true})});
app.get('/api/health',(req,res)=>res.json({ok:true,db:mongoose.connection.readyState===1}));
const seed=[['Physics Wallah','Premium learning platform','assets/physics-wallah.png'],['Next Toppers','Focused exam preparation','assets/next-toppers.png'],['Mission Jeet','Exam preparation platform','assets/mission-jeet.png'],['Unacademy','Online classes and learning','assets/unacademy.png'],['Vidyakul','Online learning and exam preparation',''],['Vibrant Academy Kota','Focused study platform','assets/vibrant-academy.png'],['Rojgar with Ankit','Government exam preparation','assets/rojgar-with-ankit.png'],['Selection Way','Government exam preparation','assets/selection-way.png'],['Careerwill','Online classes and exam preparation',''],['Target Board','E-learning platform for students','assets/target-board.png'],['Master Sahab','Advanced learning','assets/master-sahab.png']];
(async()=>{try{await mongoose.connect(process.env.MONGODB_URI);if(await App.countDocuments()===0)await App.insertMany(seed.map(x=>({name:x[0],description:x[1],logo:x[2],price:100,active:true,authorizedUrl:''})));app.listen(process.env.PORT||3000,()=>console.log('Prep Master running'));}catch(e){console.error('MongoDB connection failed:',e.message);process.exit(1)}})();
